name: Update version

jobs:
  release:
    name: Create version PR from release branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Update SDK verison
        run: yarn updateAll

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update SDK version
          title: "feat: update SDK version"
          body: Update SDK version
          branch: update-sdk-version
          base: main
          labels: version
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          draft: false
